/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CertificateNFT } from "./CertificateNFT";
export type { ScholarshipEscrow } from "./ScholarshipEscrow";
export type { VignanRegistry } from "./VignanRegistry";
