/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as certificateNftFixedSol from "./CertificateNFTFixed.sol";
export type { certificateNftFixedSol };
export type { CertificateNFT } from "./CertificateNFT";
export type { ScholarshipEscrow } from "./ScholarshipEscrow";
export type { VignanRegistry } from "./VignanRegistry";
