/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as certificateNftFixedSol from "./CertificateNFTFixed.sol";
export { CertificateNFT__factory } from "./CertificateNFT__factory";
export { ScholarshipEscrow__factory } from "./ScholarshipEscrow__factory";
export { VignanRegistry__factory } from "./VignanRegistry__factory";
